# Generated by Django 2.1.4 on 2019-03-02 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(upload_to='ServicesMedia')),
                ('image2', models.ImageField(upload_to='ServicesMedia')),
                ('image3', models.ImageField(upload_to='ServicesMedia')),
                ('image4', models.ImageField(upload_to='ServicesMedia')),
                ('image5', models.ImageField(upload_to='ServicesMedia')),
                ('description', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
