# Generated by Django 2.1.4 on 2019-03-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicesproduct_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='ServicesMedia'),
        ),
        migrations.AlterField(
            model_name='servicesproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ServicesMedia'),
        ),
        migrations.AlterField(
            model_name='servicesproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='ServicesMedia'),
        ),
        migrations.AlterField(
            model_name='servicesproduct',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='ServicesMedia'),
        ),
        migrations.AlterField(
            model_name='servicesproduct',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='ServicesMedia'),
        ),
    ]
